[versions]
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
room = "2.6.1"
kotlinpoet = "2.4.0"
junit5 = "5.10.2"
compileTesting = "0.5.1"
agp = "8.11.1"
coroutines = "1.10.2"
robolectric = "4.13"
androidxTestCore = "1.6.1"
sqlite = "2.4.0"
junit4 = "4.13.2"

[libraries]
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx     = { module = "androidx.room:room-ktx",     version.ref = "room" }
room-common  = { module = "androidx.room:room-common",  version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite        = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

robolectric     = { module = "org.robolectric:robolectric",   version.ref = "robolectric" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }

ksp-api        = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet     = { module = "com.squareup:kotlinpoet",     version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit5      = { module = "org.junit.jupiter:junit-jupiter",  version.ref = "junit5" }
junit4      = { module = "junit:junit", version.ref = "junit4" }

kotlin-compile-testing-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "compileTesting" }
kotlin-compile-testing-core = { module = "dev.zacsweers.kctfork:core", version.ref = "compileTesting" }

[plugins]
kotlin-jvm     = { id = "org.jetbrains.kotlin.jvm",     version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp            = { id = "com.google.devtools.ksp",      version.ref = "ksp" }
android-library = { id = "com.android.library",         version.ref = "agp" }
